C     ALGORITHMS AND CODE CREATED BY IOANNIS STEFANOU, 2016, PARIS
C     ALL RIGHTS RESERVED
C
      SUBROUTINE USERMATERIAL(UMATID,STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NSTR,NH,NAUXDE,UMATID
      DOUBLE PRECISION DTIME
C
	  SELECT CASE (UMATID)
		CASE (1)
			CALL USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE (2)
			!WRITE(6,*) "INFO0", NSTR
			!WRITE(6,*) "INFO1", DE
			CALL USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
			!WRITE(6,*) "INFO2", STRESS, DE
		CASE (3)
			CALL USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE DEFAULT
			WRITE(6,*) 'INVALID MATERIAL ID. CHOOSE RANGE FOR UMATID: 1 - 3'
		END SELECT
      RETURN
      END


      SUBROUTINE USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(18),FSTRESS(18)
      DOUBLE PRECISION FDSDE(18,18)
      INTEGER NOP(4),I,J
C
      INTEGER FNSTR
      FNSTR=18
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,4,16/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
	  DSDE=TRANSPOSE(DSDE)
      RETURN
      END
C
      SUBROUTINE USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(18),FSTRESS(18)
      DOUBLE PRECISION FDSDE(18,18)
      INTEGER NOP(6),I,J
C
      INTEGER FNSTR
      FNSTR=18
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,4,5,16,17/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)
      !WRITE(6,*) "INFO0", NSTR,NF,NSVARSGP,NPROPS
      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
	  DSDE=TRANSPOSE(DSDE)
      RETURN
      END
C
      SUBROUTINE USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
	  DSDE=TRANSPOSE(DSDE)
      RETURN
      END
