#materials_path="/home/alexandrosstathas/numerical_geolab_materials/UMATERIALS"
#materials_path="/mnt/c/users/alexsta_dev/numerical_geolab_materials/UMATERIALS"
#materials_path="/home/alexandrosstathas/eclipse-workspace/numerical_geolab_materials/UMATERIALS"
materials_path="/home/astathas2019/eclipse-workspace/eclipse-workspace/numerical_geolab_materials2/UMATERIALS"

mode="debug"
#mode="release"

all:
#	make -C $(materials_path)/"CAUCHY3D-AUSSOIS" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-AUSSOIS-PR-TEMP-S22-S12" $(mode)

#	make -C $(materials_path)/"CAUCHY3D-AUSSOIS-PR-TEMP-S22-S12_8_9" $(mode)

#	make -C $(materials_path)/"COSSERAT3D-AUSSOIS" $(mode)
#	make -C $(materials_path)/"COSSERAT3D-BREAKAGE-NORM" $(mode)
	make -C $(materials_path)/"COSSERAT3D-BREAKAGE" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-DP" $(mode)
#	make -C $(materials_path)/"COSSERAT3D" $(mode)

#	make -C $(materials_path)/"COSSERAT3D-THM" $(mode)

#	make -C $(materials_path)/"COSSERAT3D-EXP" $(mode)
#	make -C $(materials_path)/"CAUCHY3D" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-CAMCLAY" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-ASYMCAMCLAY" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-ASYMCAMCLAY-OLDV" $(mode)
#	make -C $(materials_path)/"NONLOCAL" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-DP" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-DP-PR" $(mode)
#	make -C $(materials_path)/"CAUCHY3D-DP-PR-TEMP" $(mode)
#	make -C $(materials_path)/"PCLAY" $(mode)
#	make -C $(materials_path)/"ELENI" $(mode)
	
	

