C     ALGORITHMS AND CODE CREATED BY IOANNIS STEFANOU, 2016, PARIS
C     ALL RIGHTS RESERVED
C
C     (byref(__UMATID),__STRESS_p,__DE_p,__AUX_DE_p,__DSDE_p,byref(__NSTRGP),byref(__AUX_DEGP),__PROPS_p,byref(__NPROPS),__SVARS_p,byref(__NSVARSGP),byref(__DTIME),byref(__NILL))
C
      SUBROUTINE UMAT ( STRESS, STATEV, DDSDDE, SSE, SPD, SCD,
     &                  RPL, DDSDDT, DRPLDE, DRPLDT,
     &                  STRAN, DSTRAN, TIME, DTIME,
     &                  TEMP, DTEMP, PREDEF, DPRED,
     &                  CMNAME, NDI, NSHR, NTENS, NSTATV,
     &                  PROPS, NPROPS, COORDS,
     &                  DROT, PNEWDT, CELENT, DFGRD0, DFGRD1,
     &                  NOEL, NPT, LAYER, KSPT, KSTEP, KINC )

C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT INTEGER(I-N)
      IMPLICIT REAL*8(A-H,O-Z)
      PARAMETER (NPRECD=2)

      CHARACTER*16  CMNAME
C
      INTEGER       NDI, NSHR, NTENS, NSTATV, NPROPS,
     &              NOEL, NPT, LAYER, KSPT, KSTEP, KINC
C
      REAL*8        STRESS(NTENS), STATEV(*),
     &              DDSDDE(NTENS,NTENS),
     &              SSE, SPD, SCD,
     &              RPL, DDSDDT(NTENS), DRPLDE(NTENS), DRPLDT,
     &              STRAN(NTENS), DSTRAN(NTENS),
     &              TIME(2), DTIME,
     &              TEMP, DTEMP, PREDEF(*), DPRED(*),
     &              PROPS(NPROPS),
     &              COORDS(3),
     &              DROT(3,3),
     &              PNEWDT,
     &              CELENT,
     &              DFGRD0(3,3), DFGRD1(3,3)

      CHARACTER*4   K4ILOI
      INTEGER NAUXDE, NUMATID, NILL
      DOUBLE PRECISION AUXDE(1)
C      K4ILOI = CMNAME(13:16)
C      IF (K4ILOI.EQ.'  04') THEN
      AUXDE=0.D0
      NAUXDE=0
      NSTR=NTENS
!
      NILL=0

      SELECT CASE (NDI)
        CASE (1)
            NUMATID=1
        CASE (2)
            NUMATID=2
        CASE (3)
            NUMATID=3

      END SELECT

      WRITE(7,*) 'WE ARE SUCCESFULL LOADING THIS THING'

      CALL USERMATERIAL(NUMATID,STRESS,DSTRAN,AUXDE,DDSDDE,NTENS,NAUXDE,
     1 PROPS,NPROPS,STATEV,NSTATV,DTIME,NILL)

      PNEWDT=1.-NILL/2.
      RETURN
      END


!      SUBROUTINE UMAT ( STRESS, STATEV, DDSDDE, SSE, SPD, SCD,
!     &                  RPL, DDSDDT, DRPLDE, DRPLDT,
!     &                  STRAN, DSTRAN, TIME, DTIME,
!     &                  TEMP, DTEMP, PREDEF, DPRED,
!     &                  CMNAME, NDI, NSHR, NTENS, NSTATV,
!     &                  PROPS, NPROPS, COORDS,
!     &                  DROT, PNEWDT, CELENT, DFGRD0, DFGRD1,
!     &                  NOEL, NPT, LAYER, KSPT, KSTEP, KINC )
!
!      IMPLICIT INTEGER(I-N)
!      IMPLICIT REAL*8(A-H,O-Z)
!      AUXDE=0.D0
!      NAUXDE=0
!      NSTR=NTENS
!
!      NILL=0
!      SELECT CASE (NDI)
!        CASE (3)
!        NUMATID=1
!        CASE (-1)
!        NUMATID=2
!        CASE (2)
!        NUMATID=3
!        CASE DEFAULT
!        NUMATID=3
!      END SELECT
!
!      CALL USERMATERIAL(NUMATID,STRESS,DSTRAN,AUXDE,DDSDDE,NSTR,NAUXDE,
!     1 PROPS,NPROPS,STATEV,NSTATV,DTIME,NILL)
!      KINC=1-NILL
!      RETURN
!      END

      SUBROUTINE USERMATERIAL(UMATID,STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NSTR,NH,NAUXDE,UMATID
      DOUBLE PRECISION DTIME
C
!      open (unit=20,file="temp.txt",action="write",status="old") ! connect unit 20 to temp.txt
!      write (20,*) "abc" ! write to temp.txt
!      WRITE(*,*) "HELLOO"

	  SELECT CASE (UMATID)
		CASE (1)
			CALL USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE (2)
			!WRITE(6,*) "INFO0", NSTR
			!WRITE(6,*) "INFO1", DE
			CALL USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
			!WRITE(6,*) "INFO2", STRESS, DE
		CASE (3)
			CALL USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE DEFAULT
			WRITE(6,*) 'INVALID MATERIAL ID. CHOOSE RANGE FOR UMATID: 1 - 3'
		END SELECT
      RETURN
      END


      SUBROUTINE USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(6),FSTRESS(6)
      DOUBLE PRECISION FDSDE(6,6)
      INTEGER NOP(2),I,J
C
      INTEGER FNSTR
      FNSTR=6
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/2,6/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
      RETURN
      END
C
      SUBROUTINE USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(6),FSTRESS(6)
      DOUBLE PRECISION FDSDE(6,6)
      INTEGER NOP(3),I,J
C
      INTEGER FNSTR
      FNSTR=6
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
!      WRITE(*,*) SVARSGP
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,6/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)
      !WRITE(6,*) "INFO0", NSTR,NF,NSVARSGP,NPROPS
      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
      RETURN
      END
C
      SUBROUTINE USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      RETURN
      END
