C     ALGORITHMS AND CODE CREATED BY IOANNIS STEFANOU, 2016, PARIS
C     ALL RIGHTS RESERVED
C
C     (byref(__UMATID),__STRESS_p,__DE_p,__AUX_DE_p,__DSDE_p,byref(__NSTRGP),byref(__AUX_DEGP),__PROPS_p,byref(__NPROPS),__SVARS_p,byref(__NSVARSGP),byref(__DTIME),byref(__NILL))
C
      SUBROUTINE USERMATERIAL(UMATID,STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NSTR,NH,UMATID,NAUXDE
      DOUBLE PRECISION DTIME
C
	  SELECT CASE (UMATID)
		CASE (1)
			CALL USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE (2)
			CALL USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE (3)
			CALL USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 		SVARSGP,NSVARSGP,DTIME,NILL)
		CASE DEFAULT
			WRITE(6,*) 'INVALID MATERIAL ID. CHOOSE RANGE FOR UMATID: 1 - 3'
		END SELECT
      RETURN
      END


      SUBROUTINE USERMAT_1D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(6),FSTRESS(6)
      DOUBLE PRECISION FDSDE(6,6)
      INTEGER NOP(2),I,J
C
      INTEGER FNSTR
      FNSTR=6
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/2,6/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
      RETURN
      END
C
      SUBROUTINE USERMAT_2D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(6),FSTRESS(6)
      DOUBLE PRECISION FDSDE(6,6)
      INTEGER NOP(3),I,J
C
      INTEGER FNSTR
      FNSTR=6
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,6/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
      RETURN
      END
C
      SUBROUTINE USERMAT_3D(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1 SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH
      DOUBLE PRECISION DTIME
C
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(STRESS,DE,DSDE,NSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      RETURN
      END
