C     ALGORITHMS AND CODE CREATED BY IOANNIS STEFANOU, 2016, PARIS
C     ALL RIGHTS RESERVED
C
C     (byref(__UMATID),__STRESS_p,__DE_p,__AUX_DE_p,__DSDE_p,byref(__NSTRGP),byref(__AUX_DEGP),__PROPS_p,byref(__NPROPS),__SVARS_p,byref(__NSVARSGP),byref(__DTIME),byref(__NILL))
C
      SUBROUTINE USERMATERIAL(UMATID,STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NSTR,NH,NAUXDE,UMATID
      DOUBLE PRECISION DTIME
C
	  SELECT CASE (UMATID)
        CASE (1) !THM1D
            CALL USERMAT_1D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1      PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
        CASE (2) !THM2D
            CALL USERMAT_2D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1      PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
        CASE (3) !THM3D
            CALL USERMAT_3D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1      PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
		CASE DEFAULT
			WRITE(6,*) 'INVALID MATERIAL ID. RANGE FOR UMATID: 1 - 3'
		END SELECT
      RETURN
      END
C
      SUBROUTINE USERMAT_1D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH,NAUXDE
      DOUBLE PRECISION DTIME,DPF,DTEMP,TEMP
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(12),FSTRESS(12),FSTRESS_EFF(12),PF
      DOUBLE PRECISION FDSDE(12,12),DE_EFF(12)
      INTEGER NOP(4),I,J
C
      INTEGER FNSTR
      FNSTR=12
      
C     SET INITIAL ZERO VALUES OF STRAIN INCREMENT
C     AND CONSTITUTIVE MATRIX TO PASS IN MATERIAL SUBROUTINE
      DE_EFF=0.D0
      FDSDE=0.D0
C     GET FLUID PRESSURE, EFFECTIVE STRESS AND TEMPERATURE
      PF=SVARSGP(53)+AUXDE(1)
      TEMP=SVARSGP(54)+AUXDE(2)
      FSTRESS_EFF=SVARSGP(1:FNSTR)
C     SET CORRESPONDANCE MATRIX
      NOP=(/2,6,8,11/)
C     GET TEMPERATURE INCREMENT AND CORRECT TOTAL STRAIN INCREMENT
      DTEMP=AUXDE(2)


!      FDE=0.D0
!      FDSDE=0.D0

      DO I=1,NSTR
        DE_EFF(NOP(I))=DE(I)
      END DO

      DO I=1,3
        DE_EFF(I)=DE_EFF(I)-PROPS(8)*DTEMP
      END DO


!      write(*,'(4F8.2)') DE_EFF

!      DO I=1,NSTR
!        FDE(NOP(I))=DE_EFF(I)
!      END DO
C
C     GET AND SET LAMBDA-STAR, BETA-STAR, RHO*C AND ALPHA
      SVARSGP(55)=PROPS(9) !LAMBDA-STAR
      SVARSGP(56)=PROPS(5) !BETA-STAR
      SVARSGP(57)=PROPS(7) !RHO*C
      SVARSGP(58)=PROPS(8) !ALPHA
C
C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS_EFF,DE_EFF,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(FSTRESS_EFF,DE_EFF,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
C     GIVE BACK
      FSTRESS=FSTRESS_EFF
      DO I=1,3
        FSTRESS(I)=FSTRESS_EFF(I)-PF
      END DO

      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
!      WRITE(*,*) STRESS
!      WRITE(*,*) SVARSGP
      SVARSGP(53)=PF
      SVARSGP(54)=TEMP
      SVARSGP(59)=DPF
      SVARSGP(60)=DTEMP
      RETURN
      END
C
      SUBROUTINE USERMAT_2D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH,NAUXDE
      DOUBLE PRECISION DTIME,DTEMP,TEMP
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(12),FSTRESS(12),FSTRESS_EFF(12),PF
      DOUBLE PRECISION FDSDE(12,12),DE_EFF(12)
      INTEGER NOP(7),I,J
C
      INTEGER FNSTR
      FNSTR=12
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,6,8,9,11,12/)
      DO I=1,NSTR
        FDE(NOP(I))=DE_EFF(I)
      END DO
C
C     GET FLUID PRESSURE, EFFECTIVE STRESS AND TEMPERATURE
      PF=SVARSGP(53)+AUXDE(1)
      TEMP=SVARSGP(54)+AUXDE(2)
      FSTRESS_EFF=SVARSGP(1:12)
C     GET TEMPERATURE INCREMENT AND CORRECT TOTAL STRAIN INCREMENT
      DTEMP=AUXDE(2)
      DE_EFF=DE
      DO I=1,3
        DE_EFF(I)=DE(I)-PROPS(8)*DTEMP
      END DO
C     GET AND SET LAMBDA-STAR, BETA-STAR, RHO*C AND ALPHA
      SVARSGP(55)=PROPS(9) !LAMBDA-STAR
      SVARSGP(56)=PROPS(5) !BETA-STAR
      SVARSGP(57)=PROPS(7) !RHO*C
      SVARSGP(58)=PROPS(8) !ALPHA
C
C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS_EFF,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(FSTRESS_EFF,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
C     GIVE BACK
      FSTRESS=FSTRESS_EFF
      DO I=1,3
        FSTRESS(I)=FSTRESS_EFF(I)-PF
      END DO
      SVARSGP(41)=PF
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
      RETURN
      END
C
      SUBROUTINE USERMAT_3D_PF_TEMP(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
      DOUBLE PRECISION FSTRESS_EFF(NSTR),DE_EFF(NSTR)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH,NAUXDE,I
      DOUBLE PRECISION DTIME,DPF,PF,DTEMP,TEMP
C
C     GET FLUID PRESSURE, EFFECTIVE STRESS AND TEMPERATURE
      DPF=AUXDE(1)
      PF=SVARSGP(53)+AUXDE(1)
      TEMP=SVARSGP(54)+AUXDE(2)
      FSTRESS_EFF=SVARSGP(1:12)
C     GET TEMPERATURE INCREMENT AND CORRECT TOTAL STRAIN INCREMENT
      DTEMP=AUXDE(2)
      DE_EFF=DE
      DO I=1,3
        DE_EFF(I)=DE(I)-PROPS(8)*DTEMP
      END DO
C     GET AND SET LAMBDA-STAR, BETA-STAR, RHO*C AND ALPHA
      SVARSGP(55)=PROPS(9) !LAMBDA-STAR
      SVARSGP(56)=PROPS(5) !BETA-STAR
      SVARSGP(57)=PROPS(7) !RHO*C
      SVARSGP(58)=PROPS(8) !ALPHA
C
!      WRITE(*,*) FSTRESS_EFF
!      WRITE(*,*) SVARSGP
      
      CALL GETNFNH(NF,NH)
      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS_EFF,DE_EFF,DSDE,NSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(FSTRESS_EFF,DE_EFF,DSDE,NSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
C
      STRESS=FSTRESS_EFF
      DO I=1,3
        STRESS(I)=FSTRESS_EFF(I)-PF
      END DO

      SVARSGP(53)=PF
      SVARSGP(54)=TEMP
      SVARSGP(59)=DPF
      SVARSGP(60)=DTEMP
      RETURN
      END

