C     ALGORITHMS AND CODE CREATED BY IOANNIS STEFANOU, 2016, PARIS
C     ALL RIGHTS RESERVED
C
      SUBROUTINE USERMATERIAL(UMATID,STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,
     1 PROPS,NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NSTR,NH,NAUXDE,UMATID
      DOUBLE PRECISION DTIME
C
	  SELECT CASE (UMATID)
		CASE (1)
			CALL USERMAT_1D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1 		NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
		CASE (2)
			!WRITE(6,*) "INFO0", NSTR
			!WRITE(6,*) "INFO1", DE
			CALL USERMAT_2D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1 		NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
			!WRITE(6,*) "INFO2", STRESS, DE
		CASE (3)
			CALL USERMAT_3D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1      NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
		CASE DEFAULT
			WRITE(6,*) 'INVALID MATERIAL ID. CHOOSE RANGE FOR UMATID: 1 - 3'
		END SELECT

      RETURN
      END


      SUBROUTINE USERMAT_1D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1      NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH, NAUXDE
      DOUBLE PRECISION DTIME,PF,DTEMP,TEMP
C     FULL SPACE VARIABLES
      DOUBLE PRECISION DE_EFF(24), FSTRESS_EFF(24)
      DOUBLE PRECISION FDSDE(24,24)
      INTEGER NOP(6),I,J
C
      INTEGER FNSTR
C     SET TOTAL NUMBER OF STRESS VALUES
      FNSTR=24
C     SET INITIAL ZERO VALUES OF STRAIN INCREMENT
C     AND CONSTITUTIVE MATRIX TO PASS IN MATERIAL SUBROUTINE
      DE_EFF=0.D0
      FDSDE=0.D0
C     GET FLUID PRESSURE, EFFECTIVE STRESS AND TEMPERATURE
      PF=SVARSGP(101)+AUXDE(1)
      TEMP=SVARSGP(102)+AUXDE(2)
      FSTRESS_EFF=SVARSGP(1:FNSTR)
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,4,16,19,22/)

C     GET TEMPERATURE INCREMENT AND CORRECT TOTAL STRAIN INCREMENT
      DTEMP=AUXDE(2)

      DO I=1,NSTR
        DE_EFF(NOP(I))=DE(I)
      END DO
!      WRITE(6,*) '>HELLO:',PROPS(13),DTEMP,PF
      DE_EFF(1)=DE(1)-PROPS(13)*DTEMP
      DE_EFF(5)=0-PROPS(13)*DTEMP
      DE_EFF(9)=0-PROPS(13)*DTEMP

!      DE_EFF(5)=0.D0
!      DE_EFF(6)=0.D0
      SVARSGP(103)=PROPS(14) !LAMBDA-STAR
      SVARSGP(104)=PROPS(10) !BETA-STAR
      SVARSGP(105)=PROPS(12) !RHO*C
      SVARSGP(106)=PROPS(13) !ALPHA



C     MATERIAL CALL
      CALL GETNFNH(NF,NH)

      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS_EFF,DE_EFF,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS_EFF,DE_EFF,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
C     UPDATE STRESS,DSDE,PF,TEMP for use in NumericalGeolab
      DO I=1,NSTR
        STRESS(I)=FSTRESS_EFF(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO

!      DO I=1,9,4
!        STRESS(I)=FSTRESS_EFF(I)-PF
!      END DO

      STRESS(1)=FSTRESS_EFF(1)-PF
!      write(6,*) fstress_eff(1),pf
      SVARSGP(101)=PF
      SVARSGP(102)=TEMP
      DSDE=TRANSPOSE(DSDE)
      SVARSGP(109)=AUXDE(1)
      SVARSGP(110)=DTEMP
!	  write(6,*)DE_EFF(24),SVARSGP(48),SVARSGP(24)
!      print '("Matrixsvarsgp"/(24F12.6,(2X)))', (SVARSGP(i), i = 1,
!     &      NSVARSGP)
      RETURN
      END
C
      SUBROUTINE USERMAT_2D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1 NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH,NAUXDE
      DOUBLE PRECISION DTIME
C     FULL SPACE VARIABLES
      DOUBLE PRECISION FDE(24),FSTRESS(24)
      DOUBLE PRECISION FDSDE(24,24)
      INTEGER NOP(10),I,J
C
      INTEGER FNSTR
      FNSTR=24 !ALEXANDROS 6/8
      FDE=0.D0
      FSTRESS=SVARSGP(1:FNSTR)
      FDSDE=0.D0
C
C     SET CORRESPONDANCE MATRIX
      NOP=(/1,2,4,5,16,17,19,20,22,23/)
      DO I=1,NSTR
        FDE(NOP(I))=DE(I)
      END DO

C     MATERIAL CALL
      CALL GETNFNH(NF,NH)
      !WRITE(6,*) "INFO0", NSTR,NF,NSVARSGP,NPROPS
      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        !DTIME=1.D0 ! to remove <-
        !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 2',FDE
        CALL USERMATMPL(FSTRESS,FDE,FDSDE,FNSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
      !WRITE(6,*) '>HELLO: MULTISURFACE PLASTICITY 3',FSTRESS
C     GIVE BACK
      DO I=1,NSTR
        STRESS(I)=FSTRESS(NOP(I))
        DO J=1,NSTR
            DSDE(I,J)=FDSDE(NOP(I),NOP(J))
        END DO
      END DO
	  DSDE=TRANSPOSE(DSDE)
      RETURN
      END
C
      SUBROUTINE USERMAT_3D(STRESS,DE,AUXDE,DSDE,NSTR,NAUXDE,PROPS,
     1 NPROPS,SVARSGP,NSVARSGP,DTIME,NILL)
C
C      INCLUDE 'ABA_PARAM.INC'
C
      IMPLICIT NONE
C
C
      INTEGER NPROPS,NSVARSGP,NILL,NF,NSTR,NH,NAUXDE,I
      DOUBLE PRECISION DTIME,PF,DTEMP,TEMP
      DOUBLE PRECISION DE(NSTR),STRESS(NSTR),AUXDE(NAUXDE)
      DOUBLE PRECISION DSDE(NSTR,NSTR)
      DOUBLE PRECISION SVARSGP(NSVARSGP),PROPS(NPROPS)

      DOUBLE PRECISION DE_EFF(NSTR),FSTRESS_EFF(NSTR)
C
C     GET FLUID PRESSURE, EFFECTIVE STRESS AND TEMPERATURE
      PF=SVARSGP(101)+AUXDE(1)
      TEMP=SVARSGP(102)+AUXDE(2)
      FSTRESS_EFF=SVARSGP(1:24)
C     GET TEMPERATURE INCREMENT AND CORRECT TOTAL STRAIN INCREMENT
      DTEMP=AUXDE(2)
      DE_EFF=DE
!      WRITE(6,*) '>HELLO:',PROPS(13),DTEMP,PF
      DO I=1,9,4
        DE_EFF(I)=DE(I)-PROPS(13)*DTEMP

      END DO
!      WRITE(6,*) DE_EFF(1), DE_EFF(5), DE_EFF(9)
C     GET AND SET LAMBDA-STAR, BETA-STAR, RHO*C AND ALPHA
      SVARSGP(103)=PROPS(14) !LAMBDA-STAR
      SVARSGP(104)=PROPS(10) !BETA-STAR
      SVARSGP(105)=PROPS(12) !RHO*C
      SVARSGP(106)=PROPS(13) !ALPHA
C
C
      CALL GETNFNH(NF,NH)
      IF (NF.EQ.0) THEN
        CALL USERMATMEL(FSTRESS_EFF,DE_EFF,DSDE,NSTR,PROPS,NPROPS,
     1      SVARSGP,NSVARSGP,NILL)
      ELSE
        CALL USERMATMPL(FSTRESS_EFF,DE_EFF,DSDE,NSTR,PROPS,NPROPS,
     1      NF,NH,SVARSGP,NSVARSGP,DTIME,NILL)
      END IF
C
      STRESS=FSTRESS_EFF
      DO I=1,9,4
        STRESS(I)=FSTRESS_EFF(I)-PF
      END DO
      SVARSGP(101)=PF
      SVARSGP(102)=TEMP
	  DSDE=TRANSPOSE(DSDE)
      !WRITE(6,*) DSDE
      !SVARSGP(110)=AUXDE(3)
      SVARSGP(109)=AUXDE(1)
      SVARSGP(110)=DTEMP
      RETURN
      END
